name: normdb_v3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alabaster=1.0.0
  - argcomplete=3.6.3
  - babel=2.18.0
  - backports.zstd=1.3.0
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.45.1
  - bioconductor-apeglm=1.24.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocparallel=1.36.0
  - bioconductor-data-packages=20260207
  - bioconductor-delayedarray=0.28.0
  - bioconductor-deseq2=1.42.0
  - bioconductor-edger=4.0.16
  - bioconductor-enhancedvolcano=1.20.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-limma=3.58.1
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.2
  - curl=8.18.0
  - cycler=0.12.1
  - deeptools=3.5.6
  - deeptoolsintervals=0.1.9
  - docutils=0.21.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gfortran_impl_linux-64=15.2.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - htslib=1.22.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - jq=1.8.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - libbigwig=0.4.8
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopenssl-static=3.6.1
  - libpng=1.6.55
  - libsanitizer=15.2.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - macs2=2.2.9.1
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - narwhals=2.16.0
  - ncurses=6.5
  - numpy=2.2.6
  - numpydoc=1.10.0
  - oniguruma=6.9.10
  - openjpeg=2.5.4
  - openssl=3.6.1
  - packaging=26.0
  - pandas=2.3.3
  - pandoc=3.9
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - plotly=6.5.2
  - pthread-stubs=0.4
  - py2bit=0.3.3
  - pybigwig=0.3.25
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pysam=0.23.3
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - r-abind=1.4_5
  - r-ashr=2.2_63
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bbmle=1.0.25.1
  - r-bdsmatrix=1.3_7
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-broom=1.0.9
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-coda=0.19_4.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.1
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.2
  - r-ellipsis=0.3.2
  - r-emdbook=1.3.14
  - r-etrunct=0.1
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gargle=1.6.0
  - r-generics=0.1.4
  - r-getopt=1.20.4
  - r-ggplot2=3.5.2
  - r-ggrepel=0.9.6
  - r-glue=1.8.0
  - r-googledrive=2.1.2
  - r-googlesheets4=1.1.2
  - r-gtable=0.3.6
  - r-haven=2.5.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-invgamma=1.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-lattice=0.22_7
  - r-lifecycle=1.0.4
  - r-locfit=1.5_9.12
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-mixsqp=0.3_54
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-mvtnorm=1.3_3
  - r-nlme=3.1_168
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-optparse=1.7.5
  - r-pillar=1.11.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.3
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=15.0.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcppnumerical=0.6_0
  - r-rcurl=1.98_1.17
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.1
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.5
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-snow=0.4_4
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.8.7
  - r-stringr=1.5.2
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-textshaping=1.0.3
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.57
  - r-truncnorm=1.0_9
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.53
  - r-xml2=1.4.0
  - r-yaml=2.3.10
  - readline=8.3
  - requests=2.32.5
  - samtools=1.22.1
  - scipy=1.15.2
  - sed=4.9
  - setuptools=82.0.0
  - six=1.17.0
  - snowballstemmer=3.0.1
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.4.0
  - tomlkit=0.14.0
  - tzdata=2025c
  - ucsc-bedgraphtobigwig=482
  - ucsc-bigwigtobedgraph=482
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - wheel=0.46.3
  - wiggletools=1.2.11
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - yq=3.4.3
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
    - cython==0.29.37
prefix: /home/roulet/anaconda3/envs/normdb_v3
